# Generated by Django 5.1 on 2024-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstance',
            unique_together={('year', 'semester', 'course')},
        ),
    ]
